<a href="https://colab.research.google.com/github/tableClothed/ML-Projects/blob/master/MovieRecommenderSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ITEM BASED

In [3]:
import pandas as pd
import numpy as np
from google.colab import files

r_cols = ['user_id', 'movie_id', 'rating']
ratings = pd.read_csv("u.data", names=r_cols, sep='\t', usecols=range(3))
ratings.head()

   user_id  movie_id  rating
0        0        50       5
1        0       172       5
2        0       133       1
3      196       242       3
4      186       302       3

In [4]:
m_cols = ['movie_id', 'title']
movies = pd.read_csv("u.item", names=m_cols, usecols=range(2), sep='|', encoding="ISO-8859-1")
movies.head()

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [5]:
ratings = pd.merge(movies, ratings)
ratings.head()

   movie_id             title  user_id  rating
0         1  Toy Story (1995)      308       4
1         1  Toy Story (1995)      287       5
2         1  Toy Story (1995)      148       4
3         1  Toy Story (1995)      280       4
4         1  Toy Story (1995)       66       3

In [6]:
user_ratings = ratings.pivot_table(index=['user_id'], columns=['title'], values='rating')
user_ratings.head()

title    'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                             ...
0                              NaN  ...                                 NaN
1                              NaN  ...                                 NaN
2                              NaN  ...                                 NaN
3                              NaN  ...                                 NaN
4                              NaN  ...                                 NaN

[5 rows x 1664 columns]

In [7]:
corr_matrix = user_ratings.corr()
corr_matrix.head()

title                      'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
title                                                 ...
'Til There Was You (1997)                        1.0  ...                                 NaN
1-900 (1994)                                     NaN  ...                                 NaN
101 Dalmatians (1996)                           -1.0  ...                                 NaN
12 Angry Men (1957)                             -0.5  ...                                 NaN
187 (1997)                                      -0.5  ...                                 NaN

[5 rows x 1664 columns]

In [8]:
# wyeliminowano dziwne wartości
corr_matrix = user_ratings.corr(method='pearson', min_periods=100)
corr_matrix.head()

title                      'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
title                                                 ...
'Til There Was You (1997)                        NaN  ...                                 NaN
1-900 (1994)                                     NaN  ...                                 NaN
101 Dalmatians (1996)                            NaN  ...                                 NaN
12 Angry Men (1957)                              NaN  ...                                 NaN
187 (1997)                                       NaN  ...                                 NaN

[5 rows x 1664 columns]

In [17]:
my_ratings = user_ratings.loc[0].dropna() # loc jest tutaj jako user id
my_ratings.head()

title
Empire Strikes Back, The (1980)    5.0
Gone with the Wind (1939)          1.0
Star Wars (1977)                   5.0
Name: 0, dtype: float64

In [18]:
similiar_candidates = pd.Series()
for i in range(0, len(my_ratings.index)):
  print("Add simulars for: " + my_ratings.index[i])

  # uzyskaj podobne
  similiars = corr_matrix[my_ratings.index[i]].dropna()

  # skalowanie podobieństwa na podstawie jak dobrze oceniony został
  similiars = similiars.map(lambda x: x * my_ratings[i])

  # dodanie wyniku do listy
  similiar_candidates = similiar_candidates.append(similiars)

print("\nSORTING...")
similiar_candidates.sort_values(inplace=True, ascending=False)
print(similiar_candidates.head(20))

Add simulars for: Empire Strikes Back, The (1980)
Add simulars for: Gone with the Wind (1939)
Add simulars for: Star Wars (1977)

SORTING...
Empire Strikes Back, The (1980)                       5.000000
Star Wars (1977)                                      5.000000
Empire Strikes Back, The (1980)                       3.741763
Star Wars (1977)                                      3.741763
Return of the Jedi (1983)                             3.606146
Return of the Jedi (1983)                             3.362779
Raiders of the Lost Ark (1981)                        2.693297
Raiders of the Lost Ark (1981)                        2.680586
Austin Powers: International Man of Mystery (1997)    1.887164
Sting, The (1973)                                     1.837692
Bridge on the River Kwai, The (1957)                  1.783717
Indiana Jones and the Last Crusade (1989)             1.750535
Cinderella (1950)                                     1.749598
Back to the Future (1985)                             1.726427
Terminator 2: Judgment Day (1991)                     1.667662
Frighteners, The (1996)                               1.663647
Field of Dreams (1989)                                1.642076
Chasing Amy (1997)                                    1.633938
L.A. Confidential (1997)                              1.595323
Dumbo (1941)                                          1.588281
dtype: float64

In [19]:
# aby sie nie powtarzały filmy
similiar_candidates = similiar_candidates.groupby(similiar_candidates.index).sum()

similiar_candidates.sort_values(inplace=True, ascending=False)
similiar_candidates.head(10)

Empire Strikes Back, The (1980)              8.877450
Star Wars (1977)                             8.870971
Return of the Jedi (1983)                    7.178172
Raiders of the Lost Ark (1981)               5.519700
Indiana Jones and the Last Crusade (1989)    3.488028
Bridge on the River Kwai, The (1957)         3.366616
Back to the Future (1985)                    3.357941
Sting, The (1973)                            3.329843
Cinderella (1950)                            3.245412
Field of Dreams (1989)                       3.222311
dtype: float64

In [20]:
# filter out movies I have already rated

filtered_similiars = similiar_candidates.drop(my_ratings.index)
filtered_similiars.head(10)

Return of the Jedi (1983)                    7.178172
Raiders of the Lost Ark (1981)               5.519700
Indiana Jones and the Last Crusade (1989)    3.488028
Bridge on the River Kwai, The (1957)         3.366616
Back to the Future (1985)                    3.357941
Sting, The (1973)                            3.329843
Cinderella (1950)                            3.245412
Field of Dreams (1989)                       3.222311
Wizard of Oz, The (1939)                     3.200268
Dumbo (1941)                                 2.981645
dtype: float64